apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: messages
  labels:
    app: api-server
    app.kubernetes.io/name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
        app.kubernetes.io/name: api-server
    spec:
      containers:
      - name: api-server
        image: messages:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: config-messages
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: messages
spec:
  selector:
    app.kubernetes.io/name: api-server
  ports:
  - name: api-server
    protocol: TCP
    port: 8080
    targetPort: 8080