apiVersion: v1
kind: ConfigMap
metadata:
  name: config-database
  namespace: messages
data:
  POSTGRES_PASSWORD: messages
  POSTGRES_USER: messages
  POSTGRES_DB: messages
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: messages
  labels:
    app: database
    app.kubernetes.io/name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        app.kubernetes.io/name: database
    spec:
      containers:
      - name: database
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: config-database
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: messages
spec:
  selector:
    app.kubernetes.io/name: database
  ports:
  - name: database
    protocol: TCP
    port: 5432
    targetPort: 5432